version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: expense_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-expense_management}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-expense_management}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: expense_backend
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbdata:
